### ISSUE TITLE
BUG: Multiple same values can't be edited together.

### ISSUE THREAD

**Issue by highvoltaged** [six7/figma-batch-styler#10]
If there are multiple values that are the same, batch styler cleverly assigns them only one number.
Except you can't change it.

create 3 styles with the following font sizes:
h1: 30px
h2: 25px
h3: 25px

If you select all 3, Batch Styler will give you: 30, 25
Try changing any of the numbers, nothing will happen.

Thanks

**Comment by six7** [comment]
Hey @highvoltaged 

Batch styler will either select all styles to that one value that you provided, or, if the amount of styles that you entered matches the length of your selected styles, will update each one with its own values.

Try entering `30, 25, 15` (or, to keep 2 the same: `30, 25, 25` while selecting all 3 styles. I hope that fixes it for you 🙏

**Comment by highvoltaged** [comment]
Ah OK, then i misunderstood how it should work.
You should still consider implementing this if not too much work.

What i would expect to happen, because Batch Styler combines those numbers, that it is possible to edit them together.

For example in this situation, h2-h4 has the same size: 45px.
http://prntscr.com/sg2jz3

Currently i cannot change any values, if there are different amount of numbers.
In this case it would be great if i could just change for example h1 60px to a diffferent number, leaving the grouped 45px the same (without entering it 3 more times.

OR: If i want to change all the 45px ones to a different number, i would just replace that one, and all the same sized ones would change.

Thanks for the clarification anyway, great plugin

**Comment by six7** [comment]
Published a new version that should solve this, give it a try!
