### ISSUE TITLE
Request: rename style name

### ISSUE THREAD

**Issue by dfdgsdfg** [six7/figma-batch-styler#12]

**Comment by jonaschafer** [comment]
+1 - I downloaded this plugin specifically for that reason.

**Comment by six7** [comment]
Shouldn't be too hard to add, will get to it on the weekend!

**Comment by jonaschafer** [comment]
Yay!

>

**Comment by six7** [comment]
Plugin is published with a new Name option, give it a try and let me know if that's good enough!
