### ISSUE TITLE
Edit style 'description'

### ISSUE THREAD

**Issue by bzupancic** [six7/figma-batch-styler#15]
Documenting styles is super important for me. Because of the way Figma hides the attributes of a style when it's created, I add those attributes (along with usage guidance) to the description.  For instance, my "body" text would have a description like this:

"This is for short paragraphs with no more than 4 lines and is commonly used in components.

Type: IBM Plex Sans
Size: 14px / 0.857rem 
Line height: 18px / 1.125rem
Weight: 400 / Regular
Letter-spacing: .16px"

I do this for every style that I create - text, color, effect, etc.

It would help tremendously to have the description input added to the plugin.

**Comment by six7** [comment]
Would you want to Batch Edit descriptions? Or only for specific styles?

I can't think of a clever way to allow editing multiple descriptions.. But if we dont need to (and just use that description for every style if multiple are selected) it would work fine
