### ISSUE TITLE
Action button hidden

### ISSUE THREAD

**Issue by stevejwikeley** [six7/figma-batch-styler#16]
First of all - thanks for building the plugin! It's great.

Other than...

🤦‍♂️ I've tried your amazing plugin with hope four times over a few months. I've never got it to work. 

Today I discovered that there is a button 'Update style' if you scroll the modal. I've been pressing the little refresh button. 

Is there anyway to make the button more obvious? Fixed button? Larger modal?

I'd assume other people don't find it too

**Comment by six7** [comment]
Woops, must have added that when I was adding more input fields. Will make the button fixed and the form scrollable! Sorry for the trouble!

**Comment by six7** [comment]
Just published a quick fix increasing the plugin's height. Will work on a more permanent fix soon.

**Comment by six7** [comment]
Decided to keep it as it is, and just increased plugin size.
