### ISSUE TITLE
Update Type Details in addition to basic properties

### ISSUE THREAD

**Issue by plainspace** [six7/figma-batch-styler#3]
More details here: 
https://spectrum.chat/figma/design-systems/question-about-build-editing-type-details-for-multiple-text-styles-aka-inter-opentype-options-type-details-text-styles-and-a-little-tailwindcss~9944365f-2988-4456-afa7-98ddd78912e8

**Comment by six7** [comment]
Hey Jared,

I had a look into what data Figma exposes to us Plugin developers, but I'm afraid type details are not part of it:

https://www.figma.com/plugin-docs/api/TextStyle

Batch Styler currently only covers
- Font Family
- Font Weight
- Size
- LineHeight

Additonal things that we could implement are:
- Text decoration
- Letter spacing
- Paragraph indent
- Paragraph spacing
- Text case

I'm afraid we'll have to wait for Figma to implement more things in their plugin api.. :/

I'll close the issue for now, as there's nothing I can do
