### ISSUE TITLE
Receiving "not a function" error on Text style update

### ISSUE THREAD

**Issue by tyocca** [six7/figma-batch-styler#4]
`stack:` "    at <anonymous> (PLUGIN_7_SOURCE)↵    at throw (native)↵    at s (PLUGIN_7_SOURCE)↵"

Let me know how I can help debug.

**Comment by six7** [comment]
Hey @tyocca!

Could you tell me what values you were trying to update - I think a screenshot of before/after could be enough!

Thanks!

**Comment by tyocca** [comment]
Hello @six7 

Yes. Here is an example of the error.

![2020-04-13 13 47 39](https://user-images.githubusercontent.com/7117606/79144779-88f77180-7d8d-11ea-9881-34599f651abf.gif)

Hope that helps!

**Comment by six7** [comment]
Thank you @tyocca - I found the issue and already pushed the update. Could you try if the newest version solves the problem? (restarting Figma should get you the newest version I think)

**Comment by tyocca** [comment]
@six7 Nice! Yes, it's working. Killer plugin by the way.
