### ISSUE TITLE
Request: Bulk Font Family changing

### ISSUE THREAD

**Issue by AndryOre** [six7/figma-batch-styler#40]
I have multiple text styles, example:
text-sm
text-md
text-base

And they all have the same font family "Inter", but I want to change it for all of them with one click and set "Roboto".

Actually this is not possible because when I select all the text styles and select the font family it automatically deselects all the styles.

**Comment by six7** [comment]
Please provide a description 🙏

**Comment by AndryOre** [comment]
Sorry, alredy edited
