### ISSUE TITLE
Line height changing to "AUTO" after update

### ISSUE THREAD

**Issue by mjsxi** [six7/figma-batch-styler#5]
When selecting multiple text styles to update and changing their `font + weight + line height` and updating it changes the first 2 properties but the `line height` changes to auto for all selected styles.

before:
<img width="401" alt="Screen Shot 2020-04-22 at 12 54 12 PM" src="https://user-images.githubusercontent.com/3400341/80010733-d748f680-8498-11ea-9980-bcaf90a545ca.png">

edited:
<img width="400" alt="Screen Shot 2020-04-22 at 12 55 36 PM" src="https://user-images.githubusercontent.com/3400341/80010748-ddd76e00-8498-11ea-9f33-267f5ecaec5c.png">

updated:
<img width="398" alt="Screen Shot 2020-04-22 at 12 56 07 PM" src="https://user-images.githubusercontent.com/3400341/80010778-e760d600-8498-11ea-9e18-ce8fd5a39aa1.png">

**Comment by mjsxi** [comment]
Also just wanted to say this is a great plugin and has saved me a bunch of time!

Much appreciation!!!

**Comment by six7** [comment]
Thanks for raising this issue. If I understand correctly you want to change line height values from 11, 12, 13, 14, 15, 16 to 12, 13, 14, 15, 17 ?

This functionality is not yet in Batch Styler, but I tried it locally and it's not too hard to add.

I'll make sure to include it in line height as well as in size, so you can pass an equal sized array to either ones, if the length matches, the line heights will change the corresponding style, if not the UI should indicate that a) the new value should be a single value or b) the length of the values should be the same as the selected styles.

**Comment by mjsxi** [comment]
Wow, thanks for this! Appreciate the update and will make bulk updating text styles much easier! 

Thanks again 👏 👏 👏

**Comment by six7** [comment]
Just published it to Figma @mjsxi - things should work now!
